# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: thedreaddpirate/metadata-query-logger/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
